// src/lib/components/Link.svelte
<script lang="ts">
	let { linkAttribute } = $props();
	console.log(linkAttribute);
</script>

<div class="inline-flex h-4 items-center justify-center gap-3">
	<div class="font-robotoflex relative justify-start text-center text-xs font-normal">
		<a href={linkAttribute.href}>{linkAttribute.name}</a>
	</div>
</div>

// components/container/Link.vue
<script lang="ts" setup>
interface Links {
  name: string
  path: string
}

const props = defineProps<{
  links: Links[]
}>()
</script>

<template>
  <div class="inline-flex items-center justify-center gap-7 py-2">
    <div v-for="(link, index) in props.links" :key="index">
      <LinkBase :path="link.path">
        {{ link.name }}
      </LinkBase>
    </div>
  </div>
</template>

<style>

</style>
